# configs/default.yaml

defaults:
  - hydra/job_logging: disabled  # Disable Hydra's default logging if needed

paths:
  project_root: ${hydra:config_path}/../..
  raw_path: ${path.project_root}/data/raw
  raw_test_path: ${path.project_root}/data/raw/test
  annotations_path: ${path.project_root}/data/annotations
  annotations_test_path: ${path.project_root}/data/annotations/test

  annotation_files:
    emotions_audio_only: "emotions_audio_only.tsv"
    emotions_audio_visual: "emotions_audio_visual.tsv"
    locations: "locations.tsv"
    music: "music.tsv"

  # Which annotation to load
  selected_annotation: "emotions_audio_visual"

data:
  batch_size: 32
  num_workers: 4

model:
  name: "model_a"
  input_size: 1000   # Adjust based on your fMRI data dimensions
  hidden_size: 256
  dropout: 0.5

training:
  num_epochs: 50
  learning_rate: 0.001

wandb:
  use_wandb: true               # Enable or disable W&B logging
  project: "DeepEmotion"        # Your W&B project name
  run_name: "experiment_1"      # Name of the run
  notes: "Initial experiment"   # Notes about this run
  tags: ["baseline", "test"]    # Tags for this run
